apiVersion: apps/v1
kind: Deployment
metadata:
  name: myfirstpoddeploy
  labels:
    app: node
spec: 
  template:
    metadata:
      name: myfirstpod
      labels:
        app: node
    spec: 
      containers:
        - name: myfirstpod
          image: abdiyu/jenkinsbuild:latest
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
  replicas: 1
  selector:
    matchLabels:
      app: node
      

